name: CI

on:
  push:
    branches:
      - "master"

jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install pnpm
      uses: pnpm/actions-setup@v2
      with:
        version: 5.x

    - name: Use node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Test
      run: |
        pnpm install
        pnpm test

